# -*- coding: utf-8 -*-
"""LVADSUSR131_vinay_I2_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3zTdCWzWslzOZMKi4H3nMmpruSCrL21
"""

#dataset
import pandas as pd
data=pd.read_csv("/content/winequality-red.csv")
df=pd.DataFrame(data)
df.head()

#find null values
df.isnull().sum()

#handle missing values
df=df.fillna(df.mean())
df.head()

#handle outliers
import matplotlib.pyplot as plt
plt.boxplot(df['fixed acidity'])
plt.show()
df=df[df['fixed acidity']<11.4]

plt.boxplot(df['free sulfur dioxide'])
plt.show()
df=df[df['free sulfur dioxide']<40]

plt.boxplot(df['total sulfur dioxide'])
plt.show()
df=df[df['total sulfur dioxide']<=104]

#data transformation
l1=[]
for i in df['quality']:
  if i<=6:
    l1.append(0)
  elif i>6 and i<=8:
    l1.append(1)
print(l1)
df['Target']=l1

#Droping duplicate rows
df.drop_duplicates(inplace=True)

#import models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score
#data splitting
X=df.drop(['Target','quality'],axis=1)
y=df['Target']

#import models
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

KNN = KNeighborsClassifier()

KNN.fit(X_train,y_train)

KNN_prediction=KNN.predict(X_test)

KNN_accuracy = accuracy_score(KNN_prediction,y_test)

print(KNN_accuracy)

#other metrics
KNN_precision= precision_score(KNN_prediction,y_test)
print(KNN_precision)

KNN_recall= recall_score(KNN_prediction,y_test)
print(KNN_recall)